-- Local test schema, without personal records or operational migration.
CREATE TABLE dealers ("id" INTEGER PRIMARY KEY, "name" TEXT, "salesforce_manager_value" TEXT, "penalty_settlement_enabled" INTEGER, "advance_enabled" INTEGER, "flat_commission_enabled" INTEGER, "van_settlement_enabled" INTEGER, "settlement_direction_visible" INTEGER, "installment_pending_enabled" INTEGER, "main_summary_cards" TEXT, "settlement_list_columns" TEXT, "merchant_list_columns" TEXT, "merchant_detail_fields" TEXT, "merchant_detail_billing_columns" TEXT, "merchant_detail_payer_columns" TEXT, "merchant_detail_installation_columns" TEXT, "bank_name" TEXT, "bank_account_number" TEXT, "active" INTEGER);
CREATE TABLE cancellation_penalties ("id" INTEGER PRIMARY KEY, "dealer_id" INTEGER, "merchant_id" INTEGER, "salesforce_case_id" TEXT, "case_number" TEXT, "status" TEXT, "amount" INTEGER, "payment_date" TEXT, "raw_payment_date" TEXT, "last_synced_at" TEXT);
CREATE TABLE dealer_rules ("id" INTEGER PRIMARY KEY, "dealer_id" INTEGER, "effective_from" TEXT, "cost_share_rate" REAL, "profit_share_rate" REAL, "vat_separate" INTEGER);
CREATE TABLE products ("id" INTEGER PRIMARY KEY, "name" TEXT, "category" TEXT, "active" INTEGER, "direct_cost_allowed" INTEGER);
CREATE TABLE product_costs ("id" INTEGER PRIMARY KEY, "product_id" INTEGER, "unit_cost" INTEGER, "condition" TEXT, "effective_from" TEXT);
CREATE TABLE dealer_product_costs ("id" INTEGER PRIMARY KEY, "dealer_id" INTEGER, "product_id" INTEGER, "unit_cost" INTEGER, "condition" TEXT, "effective_from" TEXT);
CREATE TABLE dealer_category_costs ("id" INTEGER PRIMARY KEY, "dealer_id" INTEGER, "product_category" TEXT, "unit_cost" INTEGER, "condition" TEXT, "effective_from" TEXT);
CREATE TABLE dealer_commission_rules ("id" INTEGER PRIMARY KEY, "dealer_id" INTEGER, "target_type" TEXT, "product_id" INTEGER, "product_category" TEXT, "condition" TEXT, "rental_amount" INTEGER, "contract_term_months" INTEGER, "commission_amount" INTEGER, "effective_from" TEXT);
CREATE TABLE merchants ("id" INTEGER PRIMARY KEY, "name" TEXT, "business_number" TEXT, "dealer_id" INTEGER, "install_date" TEXT, "account_status" TEXT, "salesforce_id" TEXT, "last_synced_at" TEXT);
CREATE TABLE installations ("id" INTEGER PRIMARY KEY, "merchant_id" INTEGER, "product_id" INTEGER, "quantity" INTEGER, "unit_cost_snapshot" INTEGER, "unit_cost_overridden" INTEGER, "salesforce_line_item_id" TEXT, "salesforce_case_id" TEXT, "salesforce_case_number" TEXT, "contract_install_at" TEXT, "contract_term_months" INTEGER, "condition" TEXT, "van" TEXT, "transaction_classification" TEXT, "fixing" INTEGER, "incentive" INTEGER, "fixing_payment_status" TEXT, "fixing_payment_date" TEXT, "incentive_payment_status" TEXT, "incentive_payment_date" TEXT, "fixing_settlement_month" TEXT, "incentive_settlement_month" TEXT, "sales_amount" INTEGER, "source" TEXT, "last_synced_at" TEXT);
CREATE TABLE billings ("id" INTEGER PRIMARY KEY, "merchant_id" INTEGER, "billing_month" TEXT, "billing_amount" INTEGER, "rental_revenue" INTEGER, "cancellation_revenue" INTEGER, "other_revenue" INTEGER, "purchase_type" TEXT, "installment_months" INTEGER);
CREATE TABLE dealer_members ("id" INTEGER PRIMARY KEY, "user_id" TEXT, "email" TEXT, "role" TEXT, "dealer_id" INTEGER, "active" INTEGER);
CREATE TABLE advance_payments ("id" INTEGER PRIMARY KEY, "dealer_id" INTEGER, "payment_date" TEXT, "settlement_month" TEXT, "amount" INTEGER, "memo" TEXT, "created_at" TEXT);
CREATE TABLE monthly_settlement_statuses ("id" INTEGER PRIMARY KEY, "dealer_id" INTEGER, "settlement_month" TEXT, "settlement_date" TEXT, "paid" INTEGER, "tax_invoice_issued_at" TEXT, "memo" TEXT, "paid_snapshot" TEXT, "reviewed_snapshot" TEXT, "created_at" TEXT, "updated_at" TEXT);
CREATE TABLE van_settlements ("id" INTEGER PRIMARY KEY, "dealer_id" INTEGER, "settlement_month" TEXT, "van_company" TEXT, "transaction_count" INTEGER, "payment_amount" INTEGER, "van_fee" INTEGER, "source_file" TEXT, "created_at" TEXT, "updated_at" TEXT);
CREATE TABLE payer_accounts ("id" INTEGER PRIMARY KEY, "merchant_id" INTEGER, "payer_number" TEXT, "label" TEXT, "monthly_charge" INTEGER, "billing_type" TEXT, "installment_months" INTEGER, "start_month" TEXT, "end_month" TEXT, "active" INTEGER);
CREATE TABLE payment_imports ("id" INTEGER PRIMARY KEY, "dealer_id" INTEGER, "file_name" TEXT, "imported_by" TEXT, "total_rows" INTEGER, "matched_rows" INTEGER, "unmatched_rows" INTEGER, "duplicate_rows" INTEGER, "created_at" TEXT);
CREATE TABLE payments ("id" INTEGER PRIMARY KEY, "payer_account_id" INTEGER, "merchant_id" INTEGER, "billing_month" TEXT, "payment_date" TEXT, "gross_amount" INTEGER, "supply_amount" INTEGER, "vat_amount" INTEGER, "source_file" TEXT, "external_key" TEXT, "created_at" TEXT);
